IMPORTING ALL THE NECESSARY LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

IMPORTING THE INDIAN AIR QUALITY DATASETS FOR THE DIFFERENT CITIES

In [2]:
import glob
import os

# 1. Unzip the file
!unzip -q raw_data.zip

# 2. Find all CSV files INSIDE the folder
all_files = glob.glob("raw_data/*.csv")
print(f"Found {len(all_files)} files.")

# 3. Load each CSV
dataframes = []
for filename in all_files:
    df = pd.read_csv(filename)
    dataframes.append(df)

# 4. Merge all datasets
full_df = pd.concat(dataframes, ignore_index=True)
print(f"Merged Data Shape: {full_df.shape}")

# 5. Save merged dataset
full_df.to_csv("merged_data.csv", index=False)
print("merged_data.csv saved successfully!")

Found 26 files.
Merged Data Shape: (29531, 16)
merged_data.csv saved successfully!

PREPARE THE DATASET FOR CLEANING AND PREPROCESSING

In [3]:
df = pd.read_csv("/content/merged_data.csv", encoding='latin1')

print("Dataset Ready for Cleaning!")

Dataset Ready for Cleaning!

TESTING THE DATASET

In [5]:
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Aizawl,11/03/2020,32.69,47.91,6.99,2.85,11.93,26.64,0.60,4.53,4.48,0.03,0.30,NaN,NaN,NaN
1,Aizawl,12/03/2020,31.21,38.66,7.20,1.27,10.65,25.63,0.56,4.22,2.81,0.01,0.08,NaN,52.0,Satisfactory
2,Aizawl,13/03/2020,38.39,46.68,7.19,0.91,10.37,29.16,0.57,4.46,0.18,0.00,0.00,NaN,60.0,Satisfactory
3,Aizawl,14/03/2020,43.23,50.83,7.14,1.07,10.48,28.95,0.57,4.53,0.41,0.00,0.00,NaN,62.0,Satisfactory
4,Aizawl,15/03/2020,33.82,41.03,7.09,0.36,9.73,28.41,0.48,4.63,0.30,0.00,0.00,NaN,70.0,Satisfactory

In [6]:
print("Shape of dataset:", df.shape)

Shape of dataset: (29531, 16)

CLEANING THE DATASET;

STEP 1; CHECKING FOR COLUMN INFORMATION

In [7]:
print("\nColumn information:")
df.info()

Column information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

STEP 2; CHECKING FOR MISSING DATA WITHIN EACH COLUMN

In [8]:
print("\nMissing values")
print(df.isna().sum())

Missing values
City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

STEP 3; REMOVE COLUMNS WITH OVER 50% OF DATA MISSING

In [9]:
# Drop columns with too many missing values (>50%)
missing_percent = df.isna().mean() * 100
cols_to_drop = missing_percent[missing_percent > 50].index
df.drop(columns=cols_to_drop, inplace=True)

print(f"\nDropped columns with >50% missing values: {list(cols_to_drop)}")

Dropped columns with >50% missing values: ['Xylene']

STEP 4; REPLACE MISSING POLLUTION DATA USING MEDIAN

In [10]:
# Update pollution column list
pollution_cols = [
    'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3',
    'CO', 'SO2', 'O3', 'Benzene', 'Toluene'
]

# 2. City-wise median imputation for remaining pollutants
df[pollution_cols] = (
    df
    .groupby('City')[pollution_cols]
    .transform(lambda x: x.fillna(x.median()))
)

# 3. Final safety check: fill any remaining missing values using global median
df[pollution_cols] = df[pollution_cols].fillna(
    df[pollution_cols].median()
)

# 4. Verify missing values are handled
print(df[pollution_cols].isnull().sum())

PM2.5      0
PM10       0
NO         0
NO2        0
NOx        0
NH3        0
CO         0
SO2        0
O3         0
Benzene    0
Toluene    0
dtype: int64

STEP 5; GIVEN THAT AQI (AIR QUALITY INDEX) IS THE TARGET VARIABLE, MISSING DATA WILL BE REMOVED FOR THAT ROW.

In [11]:
# Drop rows where AQI is missing
df = df.dropna(subset=['AQI'])

STEP 6; TESTING THE DATASET TO OBSERVE ANYMORE MISSING DATA

In [12]:
print("\nMissing values")
print(df.isna().sum())

Missing values
City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
AQI           0
AQI_Bucket    0
dtype: int64

STEP 7; ADJUSTING THE DATA COLUMN INTO YEARS, QUARTERLY AND MONTHS

BINNING THE YEARS

In [13]:
# Convert to datetime, invalid dates become NaT
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='%d/%m/%Y')

# Check for invalid dates
print(df[df['Date'].isna()])

# Define year bins from 2006 to 2024
year_bins = list(range(2014, 2021))  # edges
year_labels = list(range(2015, 2021))  # labels

# Bin the years
df['Year_bin'] = pd.cut(df['Date'].dt.year,
                                  bins=year_bins,
                                  labels=year_labels,
                                  include_lowest=True)

# Check
print(df[['Date', 'Year_bin']].head())

Empty DataFrame
Columns: [City, Date, PM2.5, PM10, NO, NO2, NOx, NH3, CO, SO2, O3, Benzene, Toluene, AQI, AQI_Bucket]
Index: []
        Date Year_bin
1 2020-03-12     2020
2 2020-03-13     2020
3 2020-03-14     2020
4 2020-03-15     2020
5 2020-03-16     2020

BINNING FOR QUARTERLY PERIODS

In [14]:
# Convert to datetime, invalid dates become NaT
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='%d/%m/%Y')

# Check for invalid dates
print(df[df['Date'].isna()])

# Define month bins (e.g., 1-3, 4-6, 7-9, 10-12)
month_bins = [0, 3, 6, 9, 12]  # edges
month_labels = ['Jan-Mar', 'Apr-Jun', 'Jul-Sep', 'Oct-Dec']  # labels

# Bin the months
df['Quarterly_bin'] = pd.cut(df['Date'].dt.month,
                         bins=month_bins,
                         labels=month_labels,
                         include_lowest=True)

# Check
print(df[['Date', 'Quarterly_bin']].head())

Empty DataFrame
Columns: [City, Date, PM2.5, PM10, NO, NO2, NOx, NH3, CO, SO2, O3, Benzene, Toluene, AQI, AQI_Bucket, Year_bin]
Index: []
        Date Quarterly_bin
1 2020-03-12       Jan-Mar
2 2020-03-13       Jan-Mar
3 2020-03-14       Jan-Mar
4 2020-03-15       Jan-Mar
5 2020-03-16       Jan-Mar

BINNING THE MONTHS

In [15]:
# Convert to datetime, invalid dates become NaT
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='%d/%m/%Y')

# Check for invalid dates
print(df[df['Date'].isna()])

# Define month bins (1 to 12)
month_bins = list(range(0, 13))  # edges: 0,1,2,...,12
month_labels = ['January', 'February', 'March', 'April', 'May', 'June',
                'July', 'August', 'September', 'October', 'November', 'December']

# Bin the months
df['Month_bin'] = pd.cut(df['Date'].dt.month,
                         bins=month_bins,
                         labels=month_labels,
                         include_lowest=True)

# Check
print(df[['Date', 'Month_bin']].head())

Empty DataFrame
Columns: [City, Date, PM2.5, PM10, NO, NO2, NOx, NH3, CO, SO2, O3, Benzene, Toluene, AQI, AQI_Bucket, Year_bin, Quarterly_bin]
Index: []
        Date Month_bin
1 2020-03-12     March
2 2020-03-13     March
3 2020-03-14     March
4 2020-03-15     March
5 2020-03-16     March

OBSERVING THE DATASET

In [16]:
df.head(40)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket,Year_bin,Quarterly_bin,Month_bin
1,Aizawl,2020-03-12,31.21,38.66,7.20,1.27,10.65,25.63,0.56,4.22,2.81,0.01,0.08,52.0,Satisfactory,2020,Jan-Mar,March
2,Aizawl,2020-03-13,38.39,46.68,7.19,0.91,10.37,29.16,0.57,4.46,0.18,0.00,0.00,60.0,Satisfactory,2020,Jan-Mar,March
3,Aizawl,2020-03-14,43.23,50.83,7.14,1.07,10.48,28.95,0.57,4.53,0.41,0.00,0.00,62.0,Satisfactory,2020,Jan-Mar,March
4,Aizawl,2020-03-15,33.82,41.03,7.09,0.36,9.73,28.41,0.48,4.63,0.30,0.00,0.00,70.0,Satisfactory,2020,Jan-Mar,March
5,Aizawl,2020-03-16,27.14,35.04,5.63,2.32,8.09,23.98,0.50,4.71,13.02,0.13,0.68,54.0,Satisfactory,2020,Jan-Mar,March
6,Aizawl,2020-03-17,27.32,35.75,3.07,2.14,3.41,24.57,0.48,4.84,6.03,0.25,1.34,40.0,Good,2020,Jan-Mar,March
7,Aizawl,2020-03-18,31.76,41.51,3.00,1.48,5.24,23.42,0.47,5.04,8.76,0.24,1.19,51.0,Satisfactory,2020,Jan-Mar,March
8,Aizawl,2020-03-19,43.80,53.59,2.97,1.31,4.97,23.41,0.48,5.30,9.96,0.26,1.11,63.0,Satisfactory,2020,Jan-Mar,March
9,Aizawl,2020-03-20,35.48,44.02,3.01,0.83,4.64,24.85,0.49,5.32,6.43,0.27,1.15,69.0,Satisfactory,2020,Jan-Mar,March
10,Aizawl,2020-03-21,51.27,60.05,3.01,0.88,4.62,24.44,0.49,5.63,8.62,49.66,50.11,70.0,Satisfactory,2020,Jan-Mar,March
11,Aizawl,2020-03-22,33.24,40.33,2.93,0.13,3.65,18.55,0.37,5.41,5.64,13.07,13.69,71.0,Satisfactory,2020,Jan-Mar,March
12,Aizawl,2020-03-23,35.34,41.55,2.98,0.16,3.71,20.24,0.32,5.63,5.73,62.93,62.45,53.0,Satisfactory,2020,Jan-Mar,March
13,Aizawl,2020-03-24,47.34,56.65,2.96,0.14,3.66,20.21,0.37,6.17,5.59,0.33,0.33,66.0,Satisfactory,2020,Jan-Mar,March
14,Aizawl,2020-03-25,53.64,62.86,2.96,0.17,3.77,25.43,0.44,6.75,6.44,0.23,0.84,92.0,Satisfactory,2020,Jan-Mar,March
15,Aizawl,2020-03-26,54.90,62.70,2.96,0.13,3.69,25.48,0.42,6.80,5.87,0.25,0.92,89.0,Satisfactory,2020,Jan-Mar,March
16,Aizawl,2020-03-27,44.64,53.86,2.94,0.11,3.59,28.26,0.40,7.34,6.42,0.22,0.82,82.0,Satisfactory,2020,Jan-Mar,March
17,Aizawl,2020-03-28,51.33,60.03,2.92,0.35,3.89,29.89,0.44,7.69,8.76,0.23,0.66,71.0,Satisfactory,2020,Jan-Mar,March
18,Aizawl,2020-03-29,34.54,41.95,2.93,0.13,3.64,28.47,0.36,7.80,7.99,0.19,0.60,81.0,Satisfactory,2020,Jan-Mar,March
19,Aizawl,2020-03-30,39.47,48.07,2.93,0.24,3.79,29.05,0.42,7.67,7.40,0.19,0.73,60.0,Satisfactory,2020,Jan-Mar,March
20,Aizawl,2020-03-31,27.27,33.90,2.95,0.25,3.80,30.99,0.40,7.90,6.74,0.18,0.80,51.0,Satisfactory,2020,Jan-Mar,March
21,Aizawl,2020-04-01,38.60,49.19,2.98,0.26,3.94,32.95,0.45,8.11,6.12,36.60,37.17,62.0,Satisfactory,2020,Apr-Jun,April
22,Aizawl,2020-04-02,36.22,48.66,2.93,0.25,3.86,32.94,0.40,8.36,9.24,0.15,0.55,64.0,Satisfactory,2020,Apr-Jun,April
23,Aizawl,2020-04-03,30.35,39.84,2.90,0.21,3.75,23.37,0.29,8.25,10.87,0.08,0.47,54.0,Satisfactory,2020,Apr-Jun,April
24,Aizawl,2020-04-04,24.05,41.95,2.97,0.25,3.79,21.60,0.26,8.16,11.09,0.08,0.42,43.0,Good,2020,Apr-Jun,April
25,Aizawl,2020-04-05,26.47,33.51,2.96,0.08,3.50,26.00,0.31,8.79,5.76,10.03,10.52,44.0,Good,2020,Apr-Jun,April
26,Aizawl,2020-04-06,35.13,43.65,2.96,0.15,3.69,25.10,0.31,8.49,7.94,0.12,0.52,48.0,Good,2020,Apr-Jun,April
27,Aizawl,2020-04-07,33.19,42.17,2.92,0.30,3.85,22.71,0.30,8.78,13.38,0.12,0.38,61.0,Satisfactory,2020,Apr-Jun,April
28,Aizawl,2020-04-08,24.92,31.74,2.97,0.18,3.74,23.73,0.27,8.69,9.67,0.08,0.41,45.0,Good,2020,Apr-Jun,April
29,Aizawl,2020-04-09,39.15,45.79,3.32,0.31,4.47,22.95,0.39,7.81,7.66,6.27,6.66,59.0,Satisfactory,2020,Apr-Jun,April
30,Aizawl,2020-04-10,38.01,45.39,4.41,0.13,5.70,27.97,0.41,4.52,5.62,0.16,0.70,64.0,Satisfactory,2020,Apr-Jun,April
31,Aizawl,2020-04-11,30.06,35.53,4.37,0.17,5.74,30.00,0.37,4.77,6.71,0.15,0.71,55.0,Satisfactory,2020,Apr-Jun,April
32,Aizawl,2020-04-12,21.70,27.32,4.33,0.12,5.60,26.24,0.27,4.54,8.47,8.27,8.60,41.0,Good,2020,Apr-Jun,April
33,Aizawl,2020-04-13,28.33,33.24,6.24,0.39,8.44,28.53,0.36,5.30,10.16,0.12,0.57,42.0,Good,2020,Apr-Jun,April
34,Aizawl,2020-04-14,46.26,49.81,10.26,0.45,14.04,31.28,0.47,5.66,2.97,29.29,29.74,64.0,Satisfactory,2020,Apr-Jun,April
35,Aizawl,2020-04-15,40.72,48.87,11.40,0.51,15.65,30.38,0.42,5.71,0.72,1.55,2.05,76.0,Satisfactory,2020,Apr-Jun,April
36,Aizawl,2020-04-16,22.63,28.06,11.40,0.33,15.49,23.59,0.28,5.52,0.79,4.18,4.62,49.0,Good,2020,Apr-Jun,April
37,Aizawl,2020-04-17,15.06,19.85,11.40,0.36,15.51,14.87,0.22,5.43,2.46,0.05,0.35,33.0,Good,2020,Apr-Jun,April
38,Aizawl,2020-04-18,19.50,25.12,11.44,0.25,15.38,17.65,0.25,6.06,1.17,0.05,0.31,31.0,Good,2020,Apr-Jun,April
39,Aizawl,2020-04-19,10.48,14.73,11.44,0.11,15.20,19.03,0.22,6.40,1.27,0.03,0.33,24.0,Good,2020,Apr-Jun,April
40,Aizawl,2020-04-20,11.79,18.90,11.47,0.95,16.08,19.13,0.25,6.79,8.71,1.02,1.41,24.0,Good,2020,Apr-Jun,April

TESTING TO SEE IF ANY MISSING VALUES IS REMAINING ON THE DATASET

In [17]:
print("\nMissing values")
print(df.isna().sum())

Missing values
City             0
Date             0
PM2.5            0
PM10             0
NO               0
NO2              0
NOx              0
NH3              0
CO               0
SO2              0
O3               0
Benzene          0
Toluene          0
AQI              0
AQI_Bucket       0
Year_bin         0
Quarterly_bin    0
Month_bin        0
dtype: int64

SAVING THE NEW DATASET AS PREPROCESSED AND MERGED DATA